### ISSUE TITLE
main thread panicked

### ISSUE THREAD

**Issue by njc235** [subdigital/kv-downloader#6]
I struggle with all of these command line things so please be patient.  I used to have the old nom downloader working but that stopped so I tried the kv_downloaded.  I have installed Rust ( I think) but get the following error when I run.  

thread 'main' panicked at src/tasks/download_song.rs:167:14:
can't find pitch up button: No element found

followed by 
2024-11-19T09:32:16.101913Z  INFO headless_chrome::browser: Dropping browser    
2024-11-19T09:32:16.206945Z  INFO headless_chrome::browser::process: Killing Chrome. PID: 944    
2024-11-19T09:32:16.207336Z  INFO headless_chrome::browser::transport::web_socket_connection: Sending shutdown message to message handling loop    
2024-11-19T09:32:16.207367Z  INFO headless_chrome::browser::transport: Transport incoming message loop loop received shutdown message    
2024-11-19T09:32:16.207382Z  INFO headless_chrome::browser::transport: Shutting down message handling loop    
2024-11-19T09:32:16.207406Z  INFO headless_chrome::browser::transport: cleared listeners, I think    
2024-11-19T09:32:16.208467Z  INFO headless_chrome::browser: Browser event loop received shutdown message    
2024-11-19T09:32:16.208486Z  INFO headless_chrome::browser: Finished browser's event handling loop    
2024-11-19T09:32:16.208491Z  INFO headless_chrome::browser::tab: finished tab's event handling loop    
2024-11-19T09:32:16.208513Z  INFO headless_chrome::browser::tab: finished tab's event handling loop    
2024-11-19T09:32:16.208471Z  INFO headless_chrome::browser::tab: finished tab's event handling loop    
2024-11-19T09:32:16.288770Z  INFO headless_chrome::browser::transport: dropping transport    
2024-11-19T09:32:16.288782Z  INFO headless_chrome::browser::transport::web_socket_connection: dropping websocket connection    

So I'm nearly there but something's not right.

**Comment by subdigital** [comment]
Your rust setup is working fine.

What is the exact command you're running? Assuming you are passing a value for `--transpose`, do you get an error if you don't pass that argument?

**Comment by njc235** [comment]
I used ./kv_download download [url of the file on karaoke version] no other switches or options.

**Comment by subdigital** [comment]
If you're watching the chromium browser, does the page look correct? is the URL you're using pointing to the song page?

Does the page contain this element?

<img width="118" alt="image" src="https://github.com/user-attachments/assets/69e5fddb-6622-424c-9ab4-8f42d30ee9c3">

**Comment by njc235** [comment]
Hi, yes it looks normal and does contain the key change button.

**Comment by njc235** [comment]
Here's the whole page including the command, I have *** my details.

./kv_downloader download https://www.karaoke-version.co.uk/custombackingtrack/van-morrison/brown-eyed-girl.html
2024-11-19T13:18:42.929234Z  INFO headless_chrome::browser::fetcher: Getting project dir    
2024-11-19T13:18:42.932569Z  INFO headless_chrome::browser::process: Launching Chrome binary at "/Users/njcox/Library/Application Support/headless-chrome/mac_arm-1095492/chrome-mac/Chromium.app/Contents/MacOS/Chromium"    
2024-11-19T13:18:42.934068Z  INFO headless_chrome::browser::process: Started Chrome. PID: 2482    
2024-11-19T13:18:44.997750Z  INFO headless_chrome::browser::tab: Navigating a tab to https://www.karaoke-version.co.uk    
2024-11-19T13:18:46.419260Z  INFO kv_downloader::tasks::sign_in: Using previous cookie value
2024-11-19T13:18:48.742514Z  INFO kv_downloader::tasks::sign_in: Logging in user user="*****"
2024-11-19T13:18:48.947293Z  INFO kv_downloader::tasks::sign_in: Already signed in user="*****"
2024-11-19T13:18:49.929508Z  INFO headless_chrome::browser::tab: Navigating a tab to https://www.karaoke-version.co.uk/custombackingtrack/van-morrison/brown-eyed-girl.html    
thread 'main' panicked at src/tasks/download_song.rs:167:14:
can't find pitch up button: No element found
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-11-19T13:18:53.276170Z  INFO headless_chrome::browser: Dropping browser    
2024-11-19T13:18:53.378790Z  INFO headless_chrome::browser::process: Killing Chrome. PID: 2482    
2024-11-19T13:18:53.379537Z  INFO headless_chrome::browser::transport::web_socket_connection: Sending shutdown message to message handling loop    
2024-11-19T13:18:53.379611Z  INFO headless_chrome::browser::transport: Transport incoming message loop loop received shutdown message    
2024-11-19T13:18:53.379620Z  INFO headless_chrome::browser::transport: Shutting down message handling loop    
2024-11-19T13:18:53.379644Z  INFO headless_chrome::browser::transport: cleared listeners, I think    
2024-11-19T13:18:53.379933Z  INFO headless_chrome::browser: Browser event loop received shutdown message    
2024-11-19T13:18:53.379950Z  INFO headless_chrome::browser: Finished browser's event handling loop    
2024-11-19T13:18:53.380012Z  INFO headless_chrome::browser::tab: finished tab's event handling loop    
2024-11-19T13:18:53.380062Z  INFO headless_chrome::browser::tab: finished tab's event handling loop    
2024-11-19T13:18:53.380101Z  INFO headless_chrome::browser::tab: finished tab's event handling loop    
2024-11-19T13:18:53.462700Z  INFO headless_chrome::browser::transport: dropping transport    
2024-11-19T13:18:53.462716Z  INFO headless_chrome::browser::transport::web_socket_connection: dropping websocket connection

**Comment by subdigital** [comment]
Ah, I see the issue. In the UK version the button is titled "Key up" whereas in the US version it has the title "Key Up"

🤦‍♂️ 

I'll submit a fix shortly

**Comment by njc235** [comment]
Wow!

**Comment by subdigital** [comment]
Fixed in 0.3.2

**Comment by njc235** [comment]
Thank you for the fast fix.  It is now working as expected.  You're a genius!
